name: ccswimviz-deploy
on:
  push:
    branches:
      - master
      
  workflow_dispatch:

# Jobs to be run
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter --version
